import os from "node:os";
import path from "node:path";
import { defaultGit, type GitRunner } from "./script-provenance.js";
import { expandVars, isSanctioned, parseDestination, resolveDir, walkSegments, type SanctionedEntry } from "../rules/uploads.js";

/**
 * Where a command runs, as facts the model cannot get from the command text.
 *
 * `rm -rf ./data` is harmless in a repository worktree or /tmp and ruinous in
 * a database's data directory; `git push origin main` is routine when origin
 * is the project's own forge. The command alone says neither, so the gate
 * gathers them itself: the working directory, the repository it is in, that
 * repository's remotes (credentials stripped, each marked sanctioned or not),
 * and where each destructive command's targets land. Every fact comes from a
 * short git call or path arithmetic; anything that fails is left out rather
 * than guessed.
 */
export interface CommandContext {
  cwd?: string;
  in_git_worktree?: boolean;
  repo_root?: string;
  /** Remote name to push URL, with any credentials removed, and whether it is sanctioned. */
  remotes?: Record<string, { url: string; sanctioned: boolean }>;
  /** Paths the command's destructive verbs act on, and where each lands. */
  destructive_targets?: Array<{
    command: string;
    path: string;
    /**
     * `repo` (inside the repository worktree), `repo_root_itself`, `repo_git_dir`,
     * `tmp`, `build_or_cache`, or `not_scratch` (none of those); a path can be several.
     */
    inside: string[];
    tracked?: boolean;
  }>;
}

const MAX_REMOTES = 10;
const MAX_TARGETS = 10;

/** Directory names whose contents are regenerated by a build or a tool, never kept data. */
const BUILD_OR_CACHE = new Set([
  "node_modules", "dist", "build", "target", "out", ".cache", "cache", "__pycache__", ".pytest_cache", ".mypy_cache",
  ".ruff_cache", "coverage", ".next", ".nuxt", ".turbo", ".gradle", ".venv", "venv", "bin", "obj", ".tox", ".parcel-cache",
]);

/** Verbs whose arguments are paths they delete or empty. */
const DESTRUCTIVE = new Set(["rm", "rmdir", "shred", "unlink", "truncate"]);

/** `https://user:token@host/x` -> `https://host/x`. */
export function stripUrlCredentials(url: string): string {
  return url.replace(/^([a-z][a-z0-9+.-]*:\/\/)[^/@\s]+@/i, "$1");
}

function tmpRoots(): string[] {
  return [...new Set(["/tmp", "/var/tmp", os.tmpdir()].map((p) => path.resolve(p)))];
}

function within(p: string, root: string): boolean {
  const rel = path.relative(root, p);
  return rel === "" || (!rel.startsWith("..") && !path.isAbsolute(rel));
}

function destructiveTargets(command: string, cwd: string | undefined): Array<{ command: string; path: string; cwd: string }> {
  const out: Array<{ command: string; path: string; cwd: string }> = [];
  for (const { seg, cwd: dir, vars } of walkSegments(command, cwd)) {
    if (!dir) continue;
    let targets: string[] = [];
    if (DESTRUCTIVE.has(seg.verb)) {
      // `truncate -s 0 f` and `shred -n 3 f`: a flag's value is not a target.
      const valued = seg.verb === "truncate" ? new Set(["-s", "-r"]) : seg.verb === "shred" ? new Set(["-n", "-s"]) : new Set<string>();
      for (let i = 0; i < seg.args.length; i++) {
        if (valued.has(seg.args[i])) i++;
        else if (!seg.args[i].startsWith("-")) targets.push(seg.args[i]);
      }
    } else if (seg.verb === "find" && seg.args.some((a) => a === "-delete" || a === "-exec")) {
      const firstFlag = seg.args.findIndex((a) => a.startsWith("-"));
      targets = firstFlag > 0 ? seg.args.slice(0, firstFlag) : ["."];
    } else if (seg.verb === "git" && seg.args[0] === "clean") {
      const dd = seg.args.indexOf("--");
      targets = dd === -1 ? ["."] : seg.args.slice(dd + 1);
    }
    for (const t of targets) {
      const expanded = expandVars(t, vars);
      if (expanded === undefined || /[*?[]/.test(expanded)) continue;
      const abs = resolveDir(dir, expanded);
      if (abs) out.push({ command: seg.verb === "git" ? "git clean" : seg.verb, path: abs, cwd: dir });
    }
  }
  return out.slice(0, MAX_TARGETS);
}

export function buildCommandContext(
  command: string,
  cwd: string | undefined,
  opts: { git?: GitRunner; sanctioned?: readonly SanctionedEntry[] } = {}
): CommandContext {
  const git = opts.git ?? defaultGit;
  const ctx: CommandContext = {};
  if (!cwd) return ctx;
  ctx.cwd = cwd;

  const top = git(["rev-parse", "--show-toplevel"], cwd);
  const root = top.status === 0 && top.stdout ? top.stdout.split("\n")[0].trim() : undefined;
  ctx.in_git_worktree = root !== undefined;
  if (root) {
    ctx.repo_root = root;
    const names = git(["remote"], cwd);
    if (names.status === 0 && names.stdout) {
      const remotes: NonNullable<CommandContext["remotes"]> = {};
      for (const name of names.stdout.split("\n").map((n) => n.trim()).filter(Boolean).slice(0, MAX_REMOTES)) {
        const r = git(["remote", "get-url", "--push", name], cwd);
        if (r.status !== 0 || !r.stdout) continue;
        const url = stripUrlCredentials(r.stdout.split("\n")[0].trim());
        const d = parseDestination(url);
        remotes[name] = { url, sanctioned: d === "local" || (d !== null && isSanctioned(d, opts.sanctioned ?? [])) };
      }
      if (Object.keys(remotes).length) ctx.remotes = remotes;
    }
  }

  const targets = destructiveTargets(command, cwd);
  if (targets.length) {
    ctx.destructive_targets = targets.map((t) => {
      const inside: string[] = [];
      const inRepo = root !== undefined && within(t.path, root);
      // The repository itself, or its .git, is the data, not scratch inside it.
      if (inRepo && path.resolve(t.path) === path.resolve(root!)) inside.push("repo_root_itself");
      else if (inRepo && within(t.path, path.join(root!, ".git"))) inside.push("repo_git_dir");
      else if (inRepo) inside.push("repo");
      if (tmpRoots().some((r) => within(t.path, r))) inside.push("tmp");
      // Only a build or cache directory the repository or the user's cache
      // holds counts: `/usr/bin` has a `bin` in it too.
      const home = process.env.HOME;
      const underCache = home !== undefined && within(t.path, path.join(home, ".cache"));
      const repoParts = inRepo ? path.relative(root!, t.path).split(path.sep) : [];
      if (underCache || repoParts.some((part) => BUILD_OR_CACHE.has(part))) inside.push("build_or_cache");
      if (inside.length === 0) inside.push("not_scratch");
      const entry: NonNullable<CommandContext["destructive_targets"]>[number] = { command: t.command, path: t.path, inside };
      if (inRepo) {
        const ls = git(["ls-files", "--", t.path], t.cwd);
        if (ls.status === 0) entry.tracked = ls.stdout.trim().length > 0;
      }
      return entry;
    });
  }
  return ctx;
}
